### ISSUE TITLE
【加歌頁面】修正加歌時合唱歌手順序不同時無法辨識有無重複歌曲的問題

### ISSUE THREAD

**Issue by ghost** [KenLuoTW/CrazyKTVSongMgr#10]
加歌時:
語系-歌手A&歌手B-歌名-歌曲類別
語系-歌手B&歌手A-歌名-歌曲類別
兩者除了歌手名稱以外的資料若相同,將會無視合唱歌手的順序將之視為重複歌曲。

**Comment by CrazyKTVSongMgr** [comment]
tesgd

**Comment by KenLuoTW** [comment]
加歌時:
語系-歌手A&歌手B-歌名-歌曲類別
語系-歌手B&歌手A-歌名-歌曲類別
兩者除了歌手名稱以外的資料若相同,將會無視合唱歌手的順序將之視為重複歌曲。
