### ISSUE TITLE
【歌庫設定】資料夾結構新增『\語系』及其相關檔案結構

### ISSUE THREAD

**Issue by KenLuoTW** [KenLuoTW/CrazyKTVSongMgr#68]
這是網友建議的,因為不想要有太多層的資料夾結構,但是不可避免的,檔案結構就要補足缺少的歌曲資訊,例如:

```
歌手類別_歌手_歌名

或

歌曲編號_歌手類別_歌手_歌名
```

如果要將現有歌庫轉換成新的結構,請先建立一個新的空資料夾,然後在【歌庫維護】頁面,將歌庫結構重建裡的重建資料夾設定至新的空資料夾。

接著先確定【歌庫設定】頁面裡的設定正不正確,並選擇至新的歌庫結構,因為重建歌庫結構功能是以【歌庫設定】頁面裡的設定來決定,例如歌庫加歌模式選擇『自動搬移來源 KTV 檔案至歌庫資料夾』,那麼重建時就會以搬移檔案的方式進行...等等。

最後確認沒問題之後,回到【歌庫維護】頁面,點擊重建按鈕即可。

**Comment by bobyang3** [comment]
感謝,最近很忙,沒時間測試大大的新軟體,請問下面是否支援? 謝謝!

目前我的結構是
\國語\周華健\周華健-晴天.mpg
\台語\_合唱_\周亞夢&陳亞拉-明明.mpg

先查詢歌手table,辨別歌手類別,如果找不到,就列為"未知" 好像ID=7.

**Comment by KenLuoTW** [comment]
這邊所指的歌庫結構,是指加歌模式使用搬移或複製模式時所自動建立的歌庫結構。

而你所問的是辨識方面的部份,如果是以你上面貼的結構,是可以正常辨識的:
![default](https://cloud.githubusercontent.com/assets/12954277/12253130/725f3f2c-b918-11e5-8861-5fe53b994205.png)

你的歌庫結構很明顯沒有歌曲聲道,這有可能再重新加歌時,無法辨識出正確的歌曲聲道。

至於無法辨識的歌手類別,只要在預設歌曲資訊設定即可,但是選擇其它 (ID:7)是錯誤的方式,因為其它這個歌手類別,有些人可能會加入佚名、伴唱公司...等等,如果到時數量一多,要在其它這個歌手類別找出新進歌手就不是一件易事。
![default](https://cloud.githubusercontent.com/assets/12954277/12253343/1dcb2460-b91a-11e5-9a7e-b9cb5d1e8f46.png)

你可以在預設歌曲資訊直接選擇新進歌星,加歌時加歌狀態裡會提示歌曲的歌手是新進歌星,不過還是可以直接加入歌曲。等全部歌曲加完後,你可以直接進歌手管理,查詢新進歌星,將新進歌星編輯為正確的歌手類別,變更時會同步修改該名歌手所有歌曲裡的歌手類別。

這個預設歌曲資訊是即時變動的,例如如果你要加的全是國語歌,那麼在預設歌曲資訊選擇國語後加歌,所有未有語系資訊的歌曲就都會是國語歌。

**Comment by KenLuoTW** [comment]
如果是要轉換現有歌庫結構,則不用管辨識問題,重建歌庫結構功能是依據資料庫的歌曲資料來建立新結構,而不是重新去辨識檔案來取得歌曲資料。
